use_frameworks!

platform :ios, '9.0'

target 'SettingVC_Example' do
  pod 'SettingVC', :path => '../'
#  pod 'CommonUtils', :path => '../../CommonUtils'
  target 'SettingVC_Tests' do
    inherit! :search_paths

    
  end
end
